:concurrency: 5

:queues:
  - critical
  - market_data
  - analytics
  - default
  - mailers

:scheduler:
  :schedule:
    import_historical_navs:
      cron: "15 20 * * 1-5"
      class: ImportHistoricalNavsJob
      queue: market_data